### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by pmjklemm** [waltercostamb/SSS-test#1]
1. If i download this repository and run the exemplary code of your README, the program fails with:

```
(WE) [paul@io:SSS-test]$ bash SSS.sh -i example/SIX3_AS1sub10.fa -f fasta -s Yes
Dominant base threshold is set to default (65% for 3 species and 60% for more than 3 species)
Can't open perl script "scripts/get-species.pl": No such file or directory
SIX3_AS1sub10 has only 0 species, which is not enough information to calculate the sd-ss scores
You should have at least 3 species
rm: cannot remove ‘SIX3_AS1sub10’: No such file or directory
```

This is due to the fact that you need -i -f and so on for the parameters... 

2. If you then rerun with -i ... you get another error:

```
(WE) [paul@io:SSS-test]$ bash SSS.sh -i example/SIX3_AS1sub10.fa -f fasta -s Yes 
Dominant base threshold is set to default (65% for 3 species and 60% for more than 3 species)
Can't open perl script "scripts/get-species.pl": No such file or directory
SIX3_AS1sub10 has only 0 species, which is not enough information to calculate the sd-ss scores
You should have at least 3 species
rm: cannot remove ‘SIX3_AS1sub10’: No such file or directory
```

I looked in the SSS.sh and clearly in line 84 it should not be 

> script_dir="${program_folder}scripts"

but rather

> script_dir="../${program_folder}scripts"

since you "cd" in the tmp directory. 

Greetings

**Comment by waltercostamb** [comment]
Hi pmjklemm,

look at the error: Can't open perl script "scripts/get-species.pl": No such file or directory

Bash does not find the folder "scripts/", which has perl scripts the SSS.sh needs.

Can you please send an "ls -lh" of the directory you are running the SSS-test?

Greetings

**Comment by waltercostamb** [comment]
Hi pmjklemm,

thank you for posting the bug. I fixed the code in the repository.

Greetings
